export const book_content_info = [
  "The future in your hands",
  "Where is the money",
  "The attention economy",
  "The historical evolution of the attention economy",
  "Money, power and influence: The value of what people's attention can get you",
  "Choosing the right platform to farm attention and build a strong following",
  "The algorithm",
  "Social media algorithms by platform",
  "10 tips for staying ahead of the algorithm and optimizing your content",
  "The art of branding",
  "Refined steps to build an online brand for yourself, your business or a product",
  'Using your physical "super" trait for easy attention',
  "Utilizing the theory of modelling to brand yourself",
  "The science of subconscious branding",
  "The art of creating attention grabbing video content",
  "Emotional branding/content creation",
  "Element of good content creation",
  "Understanding  different human emotion, tiggers and expressions",
  "Application of emotional states in contents",
  "Energy are contagious: The psychology",
  "Know the game and let the game know you",
  "Case study: The Tate model of branding",
  "Facebook moneitization in Nigeria: A comprehesive guide",
];

export const bookBenefits = [
  "mentoring",
  "teaching",
  "advicing",
  "Facebook",
  "whatsApp",
  "instagrem",
  "mentoring",
  "teaching",
  "advicing",
  "Facebook",
  "whatsApp",
  "instagrem",
  "mentoring",
  "teaching",
  "advicing",
  "Facebook",
  "whatsApp",
  "instagrem",
];
